// Generated by gencpp from file sdc21x0/FlagsRequest.msg
// DO NOT EDIT!


#ifndef SDC21X0_MESSAGE_FLAGSREQUEST_H
#define SDC21X0_MESSAGE_FLAGSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sdc21x0
{
template <class ContainerAllocator>
struct FlagsRequest_
{
  typedef FlagsRequest_<ContainerAllocator> Type;

  FlagsRequest_()
    : digitalPort(0)  {
    }
  FlagsRequest_(const ContainerAllocator& _alloc)
    : digitalPort(0)  {
  (void)_alloc;
    }



   typedef int32_t _digitalPort_type;
  _digitalPort_type digitalPort;





  typedef boost::shared_ptr< ::sdc21x0::FlagsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdc21x0::FlagsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FlagsRequest_

typedef ::sdc21x0::FlagsRequest_<std::allocator<void> > FlagsRequest;

typedef boost::shared_ptr< ::sdc21x0::FlagsRequest > FlagsRequestPtr;
typedef boost::shared_ptr< ::sdc21x0::FlagsRequest const> FlagsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sdc21x0::FlagsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sdc21x0::FlagsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sdc21x0::FlagsRequest_<ContainerAllocator1> & lhs, const ::sdc21x0::FlagsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.digitalPort == rhs.digitalPort;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sdc21x0::FlagsRequest_<ContainerAllocator1> & lhs, const ::sdc21x0::FlagsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sdc21x0

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sdc21x0::FlagsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdc21x0::FlagsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdc21x0::FlagsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdc21x0::FlagsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdc21x0::FlagsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdc21x0::FlagsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sdc21x0::FlagsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a48556dca33c04c7d060ef1e26808db0";
  }

  static const char* value(const ::sdc21x0::FlagsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa48556dca33c04c7ULL;
  static const uint64_t static_value2 = 0xd060ef1e26808db0ULL;
};

template<class ContainerAllocator>
struct DataType< ::sdc21x0::FlagsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sdc21x0/FlagsRequest";
  }

  static const char* value(const ::sdc21x0::FlagsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sdc21x0::FlagsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 digitalPort\n"
;
  }

  static const char* value(const ::sdc21x0::FlagsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sdc21x0::FlagsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.digitalPort);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FlagsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdc21x0::FlagsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sdc21x0::FlagsRequest_<ContainerAllocator>& v)
  {
    s << indent << "digitalPort: ";
    Printer<int32_t>::stream(s, indent + "  ", v.digitalPort);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SDC21X0_MESSAGE_FLAGSREQUEST_H
