# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mir_msgs/EncoderTestEntry.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class EncoderTestEntry(genpy.Message):
  _md5sum = "cfe8d446cf8b8eaf478f3a59f1f6abdd"
  _type = "mir_msgs/EncoderTestEntry"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 command_velocity
float64 command_distance
float64 left_dist
float64 right_dist
string suggested_direction
string user_direction
"""
  __slots__ = ['command_velocity','command_distance','left_dist','right_dist','suggested_direction','user_direction']
  _slot_types = ['float64','float64','float64','float64','string','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       command_velocity,command_distance,left_dist,right_dist,suggested_direction,user_direction

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EncoderTestEntry, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.command_velocity is None:
        self.command_velocity = 0.
      if self.command_distance is None:
        self.command_distance = 0.
      if self.left_dist is None:
        self.left_dist = 0.
      if self.right_dist is None:
        self.right_dist = 0.
      if self.suggested_direction is None:
        self.suggested_direction = ''
      if self.user_direction is None:
        self.user_direction = ''
    else:
      self.command_velocity = 0.
      self.command_distance = 0.
      self.left_dist = 0.
      self.right_dist = 0.
      self.suggested_direction = ''
      self.user_direction = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4d().pack(_x.command_velocity, _x.command_distance, _x.left_dist, _x.right_dist))
      _x = self.suggested_direction
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.user_direction
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.command_velocity, _x.command_distance, _x.left_dist, _x.right_dist,) = _get_struct_4d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.suggested_direction = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.suggested_direction = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.user_direction = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.user_direction = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4d().pack(_x.command_velocity, _x.command_distance, _x.left_dist, _x.right_dist))
      _x = self.suggested_direction
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.user_direction
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.command_velocity, _x.command_distance, _x.left_dist, _x.right_dist,) = _get_struct_4d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.suggested_direction = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.suggested_direction = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.user_direction = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.user_direction = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
