# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mir_msgs/PrecisionDockingStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PrecisionDockingStatus(genpy.Message):
  _md5sum = "17548d8189172ef51cde6fef0830938f"
  _type = "mir_msgs/PrecisionDockingStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool connected
bool motor_forward
bool motor_back
bool left_docking
bool right_docking
"""
  __slots__ = ['connected','motor_forward','motor_back','left_docking','right_docking']
  _slot_types = ['bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       connected,motor_forward,motor_back,left_docking,right_docking

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PrecisionDockingStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.connected is None:
        self.connected = False
      if self.motor_forward is None:
        self.motor_forward = False
      if self.motor_back is None:
        self.motor_back = False
      if self.left_docking is None:
        self.left_docking = False
      if self.right_docking is None:
        self.right_docking = False
    else:
      self.connected = False
      self.motor_forward = False
      self.motor_back = False
      self.left_docking = False
      self.right_docking = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5B().pack(_x.connected, _x.motor_forward, _x.motor_back, _x.left_docking, _x.right_docking))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.connected, _x.motor_forward, _x.motor_back, _x.left_docking, _x.right_docking,) = _get_struct_5B().unpack(str[start:end])
      self.connected = bool(self.connected)
      self.motor_forward = bool(self.motor_forward)
      self.motor_back = bool(self.motor_back)
      self.left_docking = bool(self.left_docking)
      self.right_docking = bool(self.right_docking)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5B().pack(_x.connected, _x.motor_forward, _x.motor_back, _x.left_docking, _x.right_docking))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.connected, _x.motor_forward, _x.motor_back, _x.left_docking, _x.right_docking,) = _get_struct_5B().unpack(str[start:end])
      self.connected = bool(self.connected)
      self.motor_forward = bool(self.motor_forward)
      self.motor_back = bool(self.motor_back)
      self.left_docking = bool(self.left_docking)
      self.right_docking = bool(self.right_docking)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5B = None
def _get_struct_5B():
    global _struct_5B
    if _struct_5B is None:
        _struct_5B = struct.Struct("<5B")
    return _struct_5B
