// Generated by gencpp from file mir_msgs/GripperState.msg
// DO NOT EDIT!


#ifndef MIR_MSGS_MESSAGE_GRIPPERSTATE_H
#define MIR_MSGS_MESSAGE_GRIPPERSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mir_msgs
{
template <class ContainerAllocator>
struct GripperState_
{
  typedef GripperState_<ContainerAllocator> Type;

  GripperState_()
    : state(0)  {
    }
  GripperState_(const ContainerAllocator& _alloc)
    : state(0)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(LOCK_UNKNOWN)
  #undef LOCK_UNKNOWN
#endif
#if defined(_WIN32) && defined(LOCK_HOMING)
  #undef LOCK_HOMING
#endif
#if defined(_WIN32) && defined(LOCK_OPEN)
  #undef LOCK_OPEN
#endif
#if defined(_WIN32) && defined(LOCK_OPENING)
  #undef LOCK_OPENING
#endif
#if defined(_WIN32) && defined(LOCK_CLOSED)
  #undef LOCK_CLOSED
#endif
#if defined(_WIN32) && defined(LOCK_CLOSING)
  #undef LOCK_CLOSING
#endif
#if defined(_WIN32) && defined(LOCK_ERROR)
  #undef LOCK_ERROR
#endif

  enum {
    LOCK_UNKNOWN = 0u,
    LOCK_HOMING = 1u,
    LOCK_OPEN = 2u,
    LOCK_OPENING = 3u,
    LOCK_CLOSED = 4u,
    LOCK_CLOSING = 6u,
    LOCK_ERROR = 9u,
  };


  typedef boost::shared_ptr< ::mir_msgs::GripperState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mir_msgs::GripperState_<ContainerAllocator> const> ConstPtr;

}; // struct GripperState_

typedef ::mir_msgs::GripperState_<std::allocator<void> > GripperState;

typedef boost::shared_ptr< ::mir_msgs::GripperState > GripperStatePtr;
typedef boost::shared_ptr< ::mir_msgs::GripperState const> GripperStateConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mir_msgs::GripperState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mir_msgs::GripperState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mir_msgs::GripperState_<ContainerAllocator1> & lhs, const ::mir_msgs::GripperState_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mir_msgs::GripperState_<ContainerAllocator1> & lhs, const ::mir_msgs::GripperState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mir_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mir_msgs::GripperState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_msgs::GripperState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mir_msgs::GripperState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mir_msgs::GripperState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_msgs::GripperState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_msgs::GripperState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mir_msgs::GripperState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4d1678902578daa427fe7bcf3c25edc";
  }

  static const char* value(const ::mir_msgs::GripperState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4d1678902578daaULL;
  static const uint64_t static_value2 = 0x427fe7bcf3c25edcULL;
};

template<class ContainerAllocator>
struct DataType< ::mir_msgs::GripperState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mir_msgs/GripperState";
  }

  static const char* value(const ::mir_msgs::GripperState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mir_msgs::GripperState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 LOCK_UNKNOWN = 0\n"
"uint8 LOCK_HOMING = 1\n"
"uint8 LOCK_OPEN = 2\n"
"uint8 LOCK_OPENING = 3\n"
"uint8 LOCK_CLOSED = 4\n"
"uint8 LOCK_CLOSING = 6\n"
"uint8 LOCK_ERROR = 9\n"
"\n"
"uint8 state\n"
;
  }

  static const char* value(const ::mir_msgs::GripperState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mir_msgs::GripperState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mir_msgs::GripperState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mir_msgs::GripperState_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIR_MSGS_MESSAGE_GRIPPERSTATE_H
