// Generated by gencpp from file mir_msgs/SkidDetectionStampedFloat.msg
// DO NOT EDIT!


#ifndef MIR_MSGS_MESSAGE_SKIDDETECTIONSTAMPEDFLOAT_H
#define MIR_MSGS_MESSAGE_SKIDDETECTIONSTAMPEDFLOAT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mir_msgs
{
template <class ContainerAllocator>
struct SkidDetectionStampedFloat_
{
  typedef SkidDetectionStampedFloat_<ContainerAllocator> Type;

  SkidDetectionStampedFloat_()
    : time_stamp()
    , value(0.0)  {
    }
  SkidDetectionStampedFloat_(const ContainerAllocator& _alloc)
    : time_stamp()
    , value(0.0)  {
  (void)_alloc;
    }



   typedef ros::Time _time_stamp_type;
  _time_stamp_type time_stamp;

   typedef double _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator> const> ConstPtr;

}; // struct SkidDetectionStampedFloat_

typedef ::mir_msgs::SkidDetectionStampedFloat_<std::allocator<void> > SkidDetectionStampedFloat;

typedef boost::shared_ptr< ::mir_msgs::SkidDetectionStampedFloat > SkidDetectionStampedFloatPtr;
typedef boost::shared_ptr< ::mir_msgs::SkidDetectionStampedFloat const> SkidDetectionStampedFloatConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator1> & lhs, const ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator2> & rhs)
{
  return lhs.time_stamp == rhs.time_stamp &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator1> & lhs, const ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mir_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fe24f6282200f91383f507e8f21daa0";
  }

  static const char* value(const ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fe24f6282200f91ULL;
  static const uint64_t static_value2 = 0x383f507e8f21daa0ULL;
};

template<class ContainerAllocator>
struct DataType< ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mir_msgs/SkidDetectionStampedFloat";
  }

  static const char* value(const ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time time_stamp\n"
"float64 value\n"
;
  }

  static const char* value(const ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_stamp);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SkidDetectionStampedFloat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mir_msgs::SkidDetectionStampedFloat_<ContainerAllocator>& v)
  {
    s << indent << "time_stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.time_stamp);
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIR_MSGS_MESSAGE_SKIDDETECTIONSTAMPEDFLOAT_H
