(cl:defpackage mir_actions-msg
  (:use )
  (:export
   "<MIRMOVEBASEACTION>"
   "MIRMOVEBASEACTION"
   "<MIRMOVEBASEACTIONFEEDBACK>"
   "MIRMOVEBASEACTIONFEEDBACK"
   "<MIRMOVEBASEACTIONGOAL>"
   "MIRMOVEBASEACTIONGOAL"
   "<MIRMOVEBASEACTIONRESULT>"
   "MIRMOVEBASEACTIONRESULT"
   "<MIRMOVEBASEFEEDBACK>"
   "MIRMOVEBASEFEEDBACK"
   "<MIRMOVEBASEGOAL>"
   "MIRMOVEBASEGOAL"
   "<MIRMOVEBASERESULT>"
   "MIRMOVEBASERESULT"
  ))

