(cl:in-package mir_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          BATTERY_PERCENTAGE-VAL
          BATTERY_PERCENTAGE
          BATTERY_TIME_REMAINING-VAL
          BATTERY_TIME_REMAINING
          BATTERY_VOLTAGE-VAL
          BATTERY_VOLTAGE
          DISTANCE_TO_NEXT_TARGET-VAL
          DISTANCE_TO_NEXT_TARGET
          ERRORS-VAL
          ERRORS
          FOOTPRINT-VAL
          FOOTPRINT
          HOOK_STATUS-VAL
          HOOK_STATUS
          HOOK_DATA-VAL
          HOOK_DATA
          MAP_ID-VAL
          MAP_ID
          UNLOADED_MAP_CHANGES-VAL
          UNLOADED_MAP_CHANGES
          MISSION_QUEUE_ID-VAL
          MISSION_QUEUE_ID
          MISSION_TEXT-VAL
          MISSION_TEXT
          MODE_ID-VAL
          MODE_ID
          MODE_TEXT-VAL
          MODE_TEXT
          MOVED-VAL
          MOVED
          POSITION-VAL
          POSITION
          ROBOT_NAME-VAL
          ROBOT_NAME
          SESSION_ID-VAL
          SESSION_ID
          SOFTWARE_VERSION-VAL
          SOFTWARE_VERSION
          STATE_ID-VAL
          STATE_ID
          STATE_TEXT-VAL
          STATE_TEXT
          UPTIME-VAL
          UPTIME
          VELOCITY-VAL
          VELOCITY
          USER_PROMPT-VAL
          USER_PROMPT
          SAFETY_SYSTEM_MUTED-VAL
          SAFETY_SYSTEM_MUTED
          JOYSTICK_LOW_SPEED_MODE_ENABLED-VAL
          JOYSTICK_LOW_SPEED_MODE_ENABLED
          JOYSTICK_WEB_SESSION_ID-VAL
          JOYSTICK_WEB_SESSION_ID
          MODE_KEY_STATE-VAL
          MODE_KEY_STATE
))